# Generated by Django 5.2.3 on 2025-06-26 17:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import myapp.models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resume",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "resume",
                "verbose_name_plural": "resumes",
            },
        ),
        migrations.AddField(
            model_name="resume",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="업로드된 이력서 파일",
                null=True,
                upload_to=myapp.models.get_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "doc", "docx"],
                        message="PDF, DOC, DOCX 파일만 업로드 가능합니다.",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="file_type",
            field=models.CharField(
                blank=True,
                choices=[("pdf", "PDF"), ("docx", "DOCX"), ("doc", "DOC")],
                help_text="파일 유형",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="file_uploaded_at",
            field=models.DateTimeField(
                blank=True, help_text="파일 업로드 시간", null=True
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="analysis_result",
            field=models.JSONField(blank=True, help_text="분석 결과 JSON", null=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="content",
            field=models.TextField(
                blank=True, help_text="이력서 내용 (텍스트)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="생성 일시"),
        ),
        migrations.AlterField(
            model_name="resume",
            name="title",
            field=models.CharField(help_text="이력서 제목", max_length=200),
        ),
        migrations.AlterField(
            model_name="resume",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="수정 일시"),
        ),
        migrations.AlterField(
            model_name="resume",
            name="user",
            field=models.ForeignKey(
                help_text="이력서를 작성한 사용자",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resumes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
